id: P004349
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5234
  title: ནང་བསྟན་གསོ་དཔྱད་ཀེ་ལ་ཤའི་ཆུ་རྒྱུན།
  author: ''
  volumes:
    e86ffa15bc5443ac82ea07a502c41d57:
      image_group_id: I3CN5236
      title: ''
      volume_number: 1
      total_pages: 80
      base_file: v001.txt
