id: I1C642196
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:59:47+00:00'
last_modified: '2022-06-07T22:11:55.011693+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5234
  title: ནང་བསྟན་གསོ་དཔྱད་ཀེ་ལ་ཤའི་ཆུ་རྒྱུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EFF7:
      image_group_id: I3CN5236
      title: ''
      total_pages: 80
      order: 1
      base_file: EFF7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
